[package]
name = "Simple_CLI"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde = { version = "1.0", features=["derive"] }

[[bin]]
name = "Simple_CLI"
path = "main.rs"
